trigger:
  - none

pr:
  branches:
    include:
    - main
    - dev
    - prod

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform-modules
      type: github
      name: MyTestOrgBallerina/TestProjectBallerina
      ref: refs/heads/master
      endpoint: security-cloud-sre-bot
